import './globals.css'
import { Inter } from 'next/font/google'
import { TanStackQueryProvider } from './Components/TanstackQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OnlineStore',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <TanStackQueryProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </TanStackQueryProvider>
  )
}
